### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Iopel/grid-template#1]
1)
несоответствие макету
![image](https://user-images.githubusercontent.com/8464662/100418955-3f456800-308c-11eb-937f-9f6ad8235f13.png)

2)
несоответствие макету
![image](https://user-images.githubusercontent.com/8464662/100419002-508e7480-308c-11eb-8d95-ba9b4212897b.png)

3)
невалидный код
![image](https://user-images.githubusercontent.com/8464662/100419050-67cd6200-308c-11eb-90cb-10dc1b99a188.png)

4)
требования к высоте не выполнены
![image](https://user-images.githubusercontent.com/8464662/100419123-921f1f80-308c-11eb-90a1-c8c417da96e4.png)

5)
требования к размеру шрифта для всех разрешений - не выполнены
![image](https://user-images.githubusercontent.com/8464662/100419152-a3682c00-308c-11eb-8d3d-1555f1e6e0f2.png)

**Comment by Iopel** [comment]
А подскажите пожалуйста, я уже высоты пыталась сделать иначе.
Но почему-то тогда, когда открывать на маленьком экране skill-item все
плохо.

Пт, 27 нояб. 2020 г. в 08:44, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
подберите высоту и минимальную высоту.
посмотрите требования к этому блоку в макету - там четко расписано.

пт, 27 лист. 2020 о 08:48 Iopel <notifications@github.com> пише:

**Comment by Iopel** [comment]
https://alecto.github.io/grid-template/

https://github.com/Iopel/grid-template.git

Готово) Простите за валидацию, я видимо что-то исправляла и не заметила
дублирование
и пункт про шрифт, я сверила раз 10, и по пикселям, и по мастер шаблону --
все одинаково. Там как-то надпись Web-developers кажется маленькой, но все
одинаково)

pt., 27 lis 2020 o 08:51 Andrey <notifications@github.com> napisał(a):

**Comment by Alecto** [comment]
теперь выглядит хорошо, больше ошибок я не вижу.
работа принята.

пт, 27 лист. 2020 о 10:03 Iopel <notifications@github.com> пише:

**Comment by Iopel** [comment]
Отличго, спасибо)

Сб, 28 нояб. 2020 г. в 15:10, Andrey <notifications@github.com>:
